package it.unitn.web.centodiciotto.utils.json;

/**
 * Entity that represents an HTML element that will be later generated by table.js.
 * <p>
 * Supports generation of any type of HTML tags, with deep support for buttons, forms, inputs, textAreas, scripts,
 * linkRefs and Selects, including their properties.
 */
@SuppressWarnings("unused")
public class HTMLElement {
    private String elementType;
    private String elementClass;
    private String elementContent;
    private String elementStyle;
    private String elementID;

    private String elementButtonType;

    private String elementInputType;
    private String elementInputName;
    private String elementInputValue;
    private String elementInputAutocomplete;

    private String elementFormAction;
    private String elementFormTarget;
    private String elementFormMethod;

    private String elementTextAreaName;
    private String elementTextAreaPlaceholder;

    private String elementScriptType;
    private String elementScriptSrc;

    private String elementLinkRel;
    private String elementLinkHref;

    private String elementSelectName;

    /**
     * Gets element input type.
     *
     * @return the element input type
     */
    public String getElementInputType() {
        return elementInputType;
    }

    /**
     * Sets element input type.
     *
     * @param elementInputType the element input type
     * @return the element input type
     */
    public HTMLElement setElementInputType(String elementInputType) {
        this.elementInputType = elementInputType;
        return this;
    }

    /**
     * Gets element input name.
     *
     * @return the element input name
     */
    public String getElementInputName() {
        return elementInputName;
    }

    /**
     * Sets element input name.
     *
     * @param elementInputName the element input name
     * @return the element input name
     */
    public HTMLElement setElementInputName(String elementInputName) {
        this.elementInputName = elementInputName;
        return this;
    }

    /**
     * Gets element input value.
     *
     * @return the element input value
     */
    public String getElementInputValue() {
        return elementInputValue;
    }

    /**
     * Sets element input value.
     *
     * @param elementInputValue the element input value
     * @return the element input value
     */
    public HTMLElement setElementInputValue(String elementInputValue) {
        this.elementInputValue = elementInputValue;
        return this;
    }

    /**
     * Gets element input autocomplete.
     *
     * @return the element input autocomplete
     */
    public String getElementInputAutocomplete() {
        return elementInputAutocomplete;
    }

    /**
     * Sets element input autocomplete.
     *
     * @param elementInputAutocomplete the element input autocomplete
     * @return the element input autocomplete
     */
    public HTMLElement setElementInputAutocomplete(String elementInputAutocomplete) {
        this.elementInputAutocomplete = elementInputAutocomplete;
        return this;
    }

    /**
     * Gets element type.
     *
     * @return the element type
     */
    public String getElementType() {
        return elementType;
    }

    /**
     * Sets element type.
     *
     * @param elementType the element type
     * @return the element type
     */
    public HTMLElement setElementType(String elementType) {
        this.elementType = elementType;
        return this;
    }

    /**
     * Gets element class.
     *
     * @return the element class
     */
    public String getElementClass() {
        return elementClass;
    }

    /**
     * Sets element class.
     *
     * @param elementClass the element class
     * @return the element class
     */
    public HTMLElement setElementClass(String elementClass) {
        this.elementClass = elementClass;
        return this;
    }

    /**
     * Gets element content.
     *
     * @return the element content
     */
    public String getElementContent() {
        return elementContent;
    }

    /**
     * Sets element content.
     *
     * @param elementContent the element content
     * @return the element content
     */
    public HTMLElement setElementContent(String elementContent) {
        this.elementContent = elementContent;
        return this;
    }

    /**
     * Gets element style.
     *
     * @return the element style
     */
    public String getElementStyle() {
        return elementStyle;
    }

    /**
     * Sets element style.
     *
     * @param elementStyle the element style
     * @return the element style
     */
    public HTMLElement setElementStyle(String elementStyle) {
        this.elementStyle = elementStyle;
        return this;
    }

    /**
     * Gets element id.
     *
     * @return the element id
     */
    public String getElementID() {
        return elementID;
    }

    /**
     * Sets element id.
     *
     * @param elementID the element id
     * @return the element id
     */
    public HTMLElement setElementID(String elementID) {
        this.elementID = elementID;
        return this;
    }

    /**
     * Gets element button type.
     *
     * @return the element button type
     */
    public String getElementButtonType() {
        return elementButtonType;
    }

    /**
     * Sets element button type.
     *
     * @param elementButtonType the element button type
     * @return the element button type
     */
    public HTMLElement setElementButtonType(String elementButtonType) {
        this.elementButtonType = elementButtonType;
        return this;
    }

    /**
     * Gets element form action.
     *
     * @return the element form action
     */
    public String getElementFormAction() {
        return elementFormAction;
    }

    /**
     * Sets element form action.
     *
     * @param elementFormAction the element form action
     * @return the element form action
     */
    public HTMLElement setElementFormAction(String elementFormAction) {
        this.elementFormAction = elementFormAction;
        return this;
    }

    /**
     * Gets element form target.
     *
     * @return the element form target
     */
    public String getElementFormTarget() {
        return elementFormTarget;
    }

    /**
     * Sets element form target.
     *
     * @param elementFormTarget the element form target
     * @return the element form target
     */
    public HTMLElement setElementFormTarget(String elementFormTarget) {
        this.elementFormTarget = elementFormTarget;
        return this;
    }

    /**
     * Gets element form method.
     *
     * @return the element form method
     */
    public String getElementFormMethod() {
        return elementFormMethod;
    }

    /**
     * Sets element form method.
     *
     * @param elementFormMethod the element form method
     * @return the element form method
     */
    public HTMLElement setElementFormMethod(String elementFormMethod) {
        this.elementFormMethod = elementFormMethod;
        return this;
    }

    /**
     * Gets element text area placeholder.
     *
     * @return the element text area placeholder
     */
    public String getElementTextAreaPlaceholder() {
        return elementTextAreaPlaceholder;
    }

    /**
     * Sets element text area placeholder.
     *
     * @param elementTextAreaPlaceholder the element text area placeholder
     * @return the element text area placeholder
     */
    public HTMLElement setElementTextAreaPlaceholder(String elementTextAreaPlaceholder) {
        this.elementTextAreaPlaceholder = elementTextAreaPlaceholder;
        return this;
    }

    /**
     * Gets element text area name.
     *
     * @return the element text area name
     */
    public String getElementTextAreaName() {
        return elementTextAreaName;
    }

    /**
     * Sets element text area name.
     *
     * @param elementTextAreaName the element text area name
     * @return the element text area name
     */
    public HTMLElement setElementTextAreaName(String elementTextAreaName) {
        this.elementTextAreaName = elementTextAreaName;
        return this;
    }

    /**
     * Gets element script type.
     *
     * @return the element script type
     */
    public String getElementScriptType() {
        return elementScriptType;
    }

    /**
     * Sets element script type.
     *
     * @param elementScriptType the element script type
     * @return the element script type
     */
    public HTMLElement setElementScriptType(String elementScriptType) {
        this.elementScriptType = elementScriptType;
        return this;
    }

    /**
     * Gets element script src.
     *
     * @return the element script src
     */
    public String getElementScriptSrc() {
        return elementScriptSrc;
    }

    /**
     * Sets element script src.
     *
     * @param elementScriptSrc the element script src
     * @return the element script src
     */
    public HTMLElement setElementScriptSrc(String elementScriptSrc) {
        this.elementScriptSrc = elementScriptSrc;
        return this;
    }

    /**
     * Gets element link rel.
     *
     * @return the element link rel
     */
    public String getElementLinkRel() {
        return elementLinkRel;
    }

    /**
     * Sets element link rel.
     *
     * @param elementLinkRel the element link rel
     * @return the element link rel
     */
    public HTMLElement setElementLinkRel(String elementLinkRel) {
        this.elementLinkRel = elementLinkRel;
        return this;
    }

    /**
     * Gets element link href.
     *
     * @return the element link href
     */
    public String getElementLinkHref() {
        return elementLinkHref;
    }

    /**
     * Sets element link href.
     *
     * @param elementLinkHref the element link href
     * @return the element link href
     */
    public HTMLElement setElementLinkHref(String elementLinkHref) {
        this.elementLinkHref = elementLinkHref;
        return this;
    }

    /**
     * Gets element select name.
     *
     * @return the element select name
     */
    public String getElementSelectName() {
        return elementSelectName;
    }

    /**
     * Sets element select name.
     *
     * @param elementSelectName the element select name
     * @return the element select name
     */
    public HTMLElement setElementSelectName(String elementSelectName) {
        this.elementSelectName = elementSelectName;
        return this;
    }
}
